data <-read.csv("household_power_consumption.txt",header=TRUE, sep=";", stringsAsFactors=FALSE, dec=".")
date <- data[data$Date=="1/2/2007", ]
date1 <- data[data$Date=="2/2/2007", ]
res <- rbind(date,date1)
datetime <- strptime(paste(res$Date, res$Time, sep=" "), "%d/%m/%Y %H:%M:%S")
plot <-as.numeric(res$Global_active_power)
volt <- as.numeric(res$Voltage)
reactive <- as.numeric(res$Global_reactive_power)
png("plot4.png",width=480,height=480)
par(mfrow=c(2,2))
plot(datetime, plot, type="l", xlab="",ylab="Global Active Power (kilowatts)")
plot(datetime, volt, type="l",ylab="Voltage")
plot(datetime, Sub_metering_1, type="l", ylab="Energy Submetering", xlab="")
  lines(datetime, Sub_metering_2, type="l", col="red")
  lines(datetime, Sub_metering_3, type="l", col="blue")
  legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1,  col=c("black", "red", "blue"))
plot(datetime,reactive,type="l",ylab="Global_reactive_power")
dev.off()
